site_name: NJIT HPC Documentation
site_url: https://arcs-njit-edu.github.io/Docs/
repo_url: https://github.com/arcs-njit-edu/Docs
#repo_name: arcs-njit-edu/Docs

nav:
    - NJIT HPC: index.md
    - 'About Us':
      - 'about/index.md'
      - 'Contact Us': 'about/contact.md'
      - 'Research Computing Advisory Board': 'about/rcab.md'
    - Clusters:
      - 'clusters/index.md'
      - 'Wulver': 'clusters/wulver.md'
      - 'Decommissioned':
        - 'Stheno': 'clusters/decommissioned/stheno.md'
        - 'Lochness': 'clusters/decommissioned/lochness.md'
      - 'User access to clusters': 'clusters/cluster_access.md'
      - 'Wulver Filesystems': 'clusters/Wulver_filesystems.md'
    - 'Getting started on Wulver': 'clusters/get_started_on_Wulver.md'
    - 'Policies':
      - 'Policies/index.md'
      - 'Wulver policy': 'Policies/wulver_policy.md'
      - 'Condo policy': 'Policies/condo_policy.md'
      - 'Allocation policy': 'Policies/allocation_policies/'
      - 'Wulver Maintenance': 'Policies/maintenance.md'
    - 'Facilities': 'facilities/facilities.md'
    - 'Services': 'Services/hpc-services.md'
    - Status (on-campus or VPN):
        - 'Current Load': 'https://hpc.njit.edu/Monitor/load.html'
        - 'Resource Usage Summary': 'https://hpc.njit.edu/Monitor/summary.html'
        - 'Resource Usage (this year so far)': 'https://hpc.njit.edu/Monitor/cy2026.html'
        - 'Application Usage': 'https://hpc.njit.edu/Monitor/modules.html'
    - HPC Events and Workshops : HPC_Events_and_Workshops/
    - Running Jobs: 
        - Overview : Running_jobs/index.md        
        - Nodes and Memory: Running_jobs/node-memory-config.md
        - Service Units (SU): Running_jobs/service-units.md
        - Batch Jobs: Running_jobs/batch-jobs.md
        - Interactive Jobs: Running_jobs/interactive-jobs.md
        - Managing and Monitoring Jobs: Running_jobs/managing-jobs.md
        - Job Limitations: Running_jobs/job_limitation.md
        - Array Jobs: Running_jobs/array-jobs.md
        - Dependency Jobs: Running_jobs/dependency-jobs.md
        - Checkpointing: Running_jobs/checkpointing.md
        - Common Problems and Misconceptions: Running_jobs/problems-and-misconceptions.md
        - Jobs on OnDemand: Running_jobs/ondemand-jobs.md
    - Software : Software/
    - MIG :
        - MIG Overview: MIG/index.md
        - Profile Comparison: MIG/profile-comparison.md
        - Job Submission and SU Charges: MIG/job-submission-and-su-charges.md
        - Performance Testing: MIG/performance_testing.md
    - OnDemand :
        - OnDemand Overview: OnDemand/index.md
        - Dashboard: OnDemand/dashboard.md
        - Apps: OnDemand/apps.md
        - Files: OnDemand/files.md
        - Jobs: OnDemand/Jobs/
        - Clusters: OnDemand/clusters.md
        - Interactive Apps: OnDemand/Interactive_Apps/
        - Tools: OnDemand/tools.md
        - My Interactive Sessions: OnDemand/my_interactive_sessions.md
        - Submit Support Ticket: OnDemand/submit_ticket.md
    - HPC for Courses :
        - Overview: Courses/index.md
        - Course Configuration: Courses/course-resource-config.md
        - Submitting Jobs: Courses/course-job-submission.md
    - 'RHEL 9 Upgrade FAQs' : 'faq/rhel_9_faq.md'
    - 'FAQs' : 'faq/faq.md'
    - 'News and Announcements' : news/index.md
    # - '' : 'website_version.txt'
    # - '' : 'archived/'


theme: 
  name: material
  logo: img/Logo_NJIT.png
  custom_dir: overrides
  favicon: favicon.ico
  palette:

    # Palette toggle for automatic mode
    #- media: "(prefers-color-scheme)"
    #  toggle:
    #    icon: material/brightness-auto
    #   name: Switch to light mode

    # Palette toggle for light mode
    #- media: "(prefers-color-scheme: light)"
    scheme: njit
     # toggle:
     #   icon: material/toggle-switch
     #   name: Switch to dark mode

    # Palette toggle for dark mode
    #- media: "(prefers-color-scheme: dark)"
    #  scheme: slate
    #  toggle:
    #    icon: material/toggle-switch-off-outline
    #    name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    #- navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - announce.dismiss
    - content.tooltips
    #- header.autohide

extra_css:
    - stylesheets/extra.css
extra:
  social:
    - icon: material/help-box-multiple
      link: https://nexus.njit.edu/highlander_nexus?id=sc_cat_item&sys_id=3f1dd0320a0a0b99000a53f7604a2ef9
      name: Contact HPC support
    - icon: fontawesome/solid/paper-plane
      link: mailto:hpc@njit.edu
      name: Email HPC support
    - icon: material/web
      link: https://ondemand.njit.edu
      name: Open OnDemand
    - icon: material/chart-areaspline
      link: https://hpc.njit.edu/Monitor/summary.html
      name: HPC job metrics

# Extensions
markdown_extensions:
  - meta
  - attr_list
  - md_in_html
  - footnotes
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols:
      fractions: false
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.blocks.caption
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

plugins:
  - search
  - markdown-exec
  - table-reader
  - mkdocstrings
  - awesome-pages
  - literate-nav
  - autolinks
  - blog:
      blog_dir: news
      #authors: false
      #archive: false
  - tags

copyright: New Jersey Institute of Technology High Performance Computing &copy; 2026
